env:
  - GO111MODULE=on
builds:
  - id: starboard-octant-plugin
    main: ./cmd/starboard-octant-plugin/main.go
    binary: starboard-octant-plugin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .FullCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
