name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: make test
      - name: Release snapshot
        uses: goreleaser/goreleaser-action@v2
        with:
          verson: v0.143.0
          args: release --snapshot --skip-publish --rm-dist
